development:
  adapter: postgresql
  encoding: unicode
  database: fledgg
  host: localhost
  username: fledgg
  password: 
test:
  adapter: postgresql
  encoding: unicode
  database: fledgg_test
  host: localhost
  pool: 5
  username: fledgg
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: fledgg_production
  pool: 25
  username: fledgg
  password:
