development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: vicky@fledgg.com
  :password: REDACTED
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: vicky@fledgg.com
  :password: REDACTED
  :enable_starttls_auto: true





